# Generated by Django 4.1.6 on 2023-02-27 07:05

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(1990, 1, 1)),
        ),
        migrations.AlterField(
            model_name='update_competency',
            name='state',
            field=models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Disable', max_length=8, verbose_name='state'),
        ),
        migrations.CreateModel(
            name='training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=50, verbose_name='Training Name')),
                ('training_description', models.TextField(max_length=500, verbose_name='Training Description')),
                ('training_date', models.DateTimeField(verbose_name='Training Date & Time')),
                ('training_duration', models.IntegerField(help_text='Enter number in hours', verbose_name='Training Duration')),
                ('training_location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Training Location')),
                ('training_link', models.URLField(verbose_name='Training Link')),
                ('training_members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
