# Generated by Django 4.1.6 on 2023-02-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_user_date_of_birth_alter_update_competency_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_temp', models.CharField(blank=True, max_length=50, null=True, verbose_name='Temp Mode Name')),
            ],
        ),
    ]
