# Generated by Django 4.1.6 on 2023-03-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_temp_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20)),
                ('comments', models.TextField(max_length=500, verbose_name='add comments')),
            ],
        ),
        migrations.DeleteModel(
            name='temp_mode',
        ),
    ]
